[project]
name = "Image2Biomass"
version = "0.1.0"
description = "Project for kaggle competition Image2Biomass"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
]
